REM INSERTING into DBUSER.STATE
SET DEFINE OFF;
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1321,'Alabama','AL',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1324,'Alaska','AK',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1327,'Arizona','AZ',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1330,'Arkansas','AR',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1333,'California','CA',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1336,'Colorado','CO',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1339,'Connecticut','CT',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1342,'Delaware','DE',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1345,'Florida','FL',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1348,'Georgia','GA',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1351,'Hawaii','HI',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1354,'Idaho','ID',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1357,'Illinois','IL',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1360,'Indiana','IN',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1363,'Iowa','IA',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1366,'Kansas','KS',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1369,'Kentucky','KY',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1372,'Louisiana','LA',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1375,'Maine','ME',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1378,'Maryland','MD',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1381,'Massachusetts','MA',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1384,'Michigan','MI',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1387,'Minnesota','MN',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1390,'Mississippi','MS',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1393,'Missouri','MO',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1396,'Montana','MT',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1399,'Nebraska','NE',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1402,'Nevada','NV',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1405,'New Hampshire','NH',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1408,'New Jersey','NJ',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1411,'New Mexico','NM',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1414,'New York','NY',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1417,'North Carolina','NC',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1420,'North Dakota','ND',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1423,'Ohio','OH',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1426,'Oklahoma','OK',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1429,'Oregon','OR',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1432,'Pennsylvania','PA',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1435,'Rhode Island','RI',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1438,'South Carolina','SC',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1441,'South Dakota','SD',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1444,'Tennessee','TN',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1447,'Texas','TX',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1450,'Utah','UT',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1453,'Vermont','VT',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1456,'Virginia','VA',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1459,'Washington','WA',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1462,'West Virginia','WV',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1465,'Wisconsin','WI',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1468,'Wyoming','WY',1);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1471,'Alberta','AB',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1474,'British Columbia','BC',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1477,'Manitoba','MB',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1480,'New Brunswick','NB',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1483,'Newfoundland and Labrador','NL',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1486,'Nova Scotia','NS',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1489,'Northwest Territories','NT',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1492,'Nunavut','NU',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1495,'Ontario','ON',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1498,'Prince Edward Island','PE',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1501,'Quebec','QC',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1504,'Saskatchewan','SK',2);
Insert into DBUSER.STATE (ID,NAME,CODE,COUNTRY_ID) values (1507,'Yukon','YT',2);
